import React, { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';

const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];

function Billing() {
  const { user } = useAuth();
  const [bills, setBills] = useState([]);
  const [flats, setFlats] = useState([]);
  const [formData, setFormData] = useState({
    flat_id: '', month: 'January', year: new Date().getFullYear(),
    maintenance_amount: 0, water_charge: 0, electricity_charge: 0, other_charges: 0
  });
  const [showModal, setShowModal] = useState(false);
  const [editBill, setEditBill] = useState(null);
  const [viewBill, setViewBill] = useState(null);

  useEffect(() => {
    fetchBills();
    fetchFlats();
  }, []);

  const fetchBills = async () => {
    try {
      const res = await axios.get('http://127.0.0.1:5000/api/bills');
      setBills(res.data);
    } catch (err) { console.error(err); }
  };

  const fetchFlats = async () => {
    try {
      const res = await axios.get('http://127.0.0.1:5000/api/flats');
      setFlats(res.data);
    } catch (err) { console.error(err); }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      if (editBill) {
        await axios.put(`http://127.0.0.1:5000/api/bills/${editBill.id}`, formData);
      } else {
        await axios.post('http://127.0.0.1:5000/api/bills', formData);
      }
      closeModal();
      fetchBills();
    } catch (err) { alert("Error saving bill"); }
  };

  const handleDelete = async (id) => {
    if (!window.confirm("Delete this bill?")) return;
    try {
      await axios.delete(`http://127.0.0.1:5000/api/bills/${id}`);
      fetchBills();
    } catch (err) { alert("Error deleting bill"); }
  };

  const openEdit = (bill) => {
    setEditBill(bill);
    setFormData({
      flat_id: bill.flat_id, month: bill.month, year: bill.year,
      maintenance_amount: bill.maintenance_amount, water_charge: bill.water_charge,
      electricity_charge: bill.electricity_charge, other_charges: bill.other_charges
    });
    setShowModal(true);
  };

  const closeModal = () => {
    setShowModal(false);
    setEditBill(null);
    setFormData({ flat_id: '', month: 'January', year: new Date().getFullYear(), maintenance_amount: 0, water_charge: 0, electricity_charge: 0, other_charges: 0 });
  };

  const printBill = (bill) => {
    const win = window.open('', '_blank');
    win.document.write(`
      <html><head><title>Bill #BL-${bill.id}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #111; }
        .header { text-align: center; border-bottom: 2px solid #6366f1; padding-bottom: 20px; margin-bottom: 20px; }
        .header h1 { color: #6366f1; margin: 0; }
        .row { display: flex; justify-content: space-between; margin: 10px 0; padding: 8px 0; border-bottom: 1px solid #eee; }
        .label { color: #666; }
        .total { font-size: 1.3rem; font-weight: bold; color: #6366f1; }
        .badge { padding: 4px 12px; border-radius: 20px; font-size: 0.85rem; }
        .paid { background: #dcfce7; color: #166534; }
        .pending { background: #fef9c3; color: #854d0e; }
        @media print { button { display: none; } }
      </style></head><body>
      <div class="header">
        <h1>🏢 Apt Manager</h1>
        <h2>Maintenance Bill</h2>
        <p>Bill #BL-${bill.id}</p>
      </div>
      <div class="row"><span class="label">Flat Number</span><span>${bill.flat_id}</span></div>
      <div class="row"><span class="label">Billing Period</span><span>${bill.month} ${bill.year}</span></div>
      <div class="row"><span class="label">Maintenance</span><span>₹${bill.maintenance_amount.toLocaleString('en-IN')}</span></div>
      <div class="row"><span class="label">Water Charge</span><span>₹${bill.water_charge.toLocaleString('en-IN')}</span></div>
      <div class="row"><span class="label">Electricity Charge</span><span>₹${bill.electricity_charge.toLocaleString('en-IN')}</span></div>
      <div class="row"><span class="label">Other Charges</span><span>₹${bill.other_charges.toLocaleString('en-IN')}</span></div>
      <div class="row total"><span>Total Amount</span><span>₹${bill.total_amount.toLocaleString('en-IN')}</span></div>
      <div class="row"><span class="label">Status</span><span class="badge ${bill.status === 'Paid' ? 'paid' : 'pending'}">${bill.status}</span></div>
      <p style="text-align:center;margin-top:40px;color:#999;font-size:0.8rem">Generated by Apt Manager System</p>
      <button onclick="window.print()" style="margin:20px auto;display:block;padding:10px 30px;background:#6366f1;color:white;border:none;border-radius:8px;cursor:pointer;font-size:1rem">🖨️ Print / Save PDF</button>
      </body></html>
    `);
    win.document.close();
  };

  return (
    <div>
      <div className="d-flex justify-content-between align-items-center mb-4">
        <p className="text-muted mb-0">Maintenance Bills & Charges (₹)</p>
        {user?.role === 'admin' && (
          <button className="btn btn-primary-gradient" onClick={() => setShowModal(true)}>
            <i className="bi bi-receipt me-1"></i> Generate Bill
          </button>
        )}
      </div>

      <div className="glass-card p-4">
        <div className="table-responsive">
          <table className="table table-borderless table-glass text-center align-middle">
            <thead>
              <tr>
                <th>Bill ID</th>
                <th>Flat No.</th>
                <th>Period</th>
                <th>Maintenance</th>
                <th>Water</th>
                <th>Electricity</th>
                <th>Total</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {bills.length === 0 ? (
                <tr><td colSpan="9" className="text-muted py-4">No bills generated yet.</td></tr>
              ) : (
                bills.map(b => (
                  <tr key={b.id}>
                    <td className="fw-bold">#BL-{b.id}</td>
                    <td><span className="badge bg-dark border border-secondary text-primary">{b.flat_id}</span></td>
                    <td>{b.month} {b.year}</td>
                    <td>₹{b.maintenance_amount.toLocaleString('en-IN')}</td>
                    <td>₹{b.water_charge.toLocaleString('en-IN')}</td>
                    <td>₹{b.electricity_charge.toLocaleString('en-IN')}</td>
                    <td className="fw-bold text-primary">₹{b.total_amount.toLocaleString('en-IN')}</td>
                    <td>
                      <span className={`badge ${b.status === 'Paid' ? 'bg-success' : 'bg-warning text-dark'}`}>
                        {b.status}
                      </span>
                    </td>
                    <td>
                      <div className="d-flex gap-1 justify-content-center">
                        <button className="btn btn-sm btn-outline-info" onClick={() => printBill(b)} title="Download PDF">
                          <i className="bi bi-download"></i>
                        </button>
                        {user?.role === 'admin' && b.status === 'Pending' && (
                          <button className="btn btn-sm btn-outline-warning" onClick={() => openEdit(b)} title="Edit">
                            <i className="bi bi-pencil"></i>
                          </button>
                        )}
                        {user?.role === 'admin' && (
                          <button className="btn btn-sm btn-outline-danger" onClick={() => handleDelete(b.id)} title="Delete">
                            <i className="bi bi-trash"></i>
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Generate / Edit Bill Modal */}
      {showModal && (
        <div className="modal show d-block" tabIndex="-1" style={{ backgroundColor: 'rgba(0,0,0,0.5)' }}>
          <div className="modal-dialog modal-dialog-centered modal-lg" data-bs-theme="dark">
            <div className="modal-content glass-card">
              <div className="modal-header border-secondary border-bottom">
                <h5 className="modal-title fw-bold">
                  {editBill ? `Edit Bill #BL-${editBill.id}` : 'Generate New Bill'}
                </h5>
                <button type="button" className="btn-close" onClick={closeModal}></button>
              </div>
              <form onSubmit={handleSubmit}>
                <div className="modal-body">
                  <div className="row">
                    <div className="col-md-4 mb-3">
                      <label className="form-label text-muted">Select Flat</label>
                      <select className="form-select" value={formData.flat_id} onChange={e => setFormData({ ...formData, flat_id: e.target.value })} required>
                        <option value="">Choose...</option>
                        {flats.map(f => <option key={f.id} value={f.flat_id}>{f.flat_id} (Block {f.block})</option>)}
                      </select>
                    </div>
                    <div className="col-md-4 mb-3">
                      <label className="form-label text-muted">Month</label>
                      <select className="form-select" value={formData.month} onChange={e => setFormData({ ...formData, month: e.target.value })}>
                        {MONTHS.map(m => <option key={m} value={m}>{m}</option>)}
                      </select>
                    </div>
                    <div className="col-md-4 mb-3">
                      <label className="form-label text-muted">Year</label>
                      <input type="number" className="form-control" value={formData.year} onChange={e => setFormData({ ...formData, year: e.target.value })} required />
                    </div>
                  </div>
                  <div className="row">
                    <div className="col-md-6 mb-3">
                      <label className="form-label text-muted">Maintenance Fee (₹)</label>
                      <input type="number" step="0.01" className="form-control" value={formData.maintenance_amount} onChange={e => setFormData({ ...formData, maintenance_amount: e.target.value })} required />
                    </div>
                    <div className="col-md-6 mb-3">
                      <label className="form-label text-muted">Water Charge (₹)</label>
                      <input type="number" step="0.01" className="form-control" value={formData.water_charge} onChange={e => setFormData({ ...formData, water_charge: e.target.value })} />
                    </div>
                  </div>
                  <div className="row">
                    <div className="col-md-6 mb-3">
                      <label className="form-label text-muted">Electricity Charge (₹)</label>
                      <input type="number" step="0.01" className="form-control" value={formData.electricity_charge} onChange={e => setFormData({ ...formData, electricity_charge: e.target.value })} />
                    </div>
                    <div className="col-md-6 mb-3">
                      <label className="form-label text-muted">Other Charges (₹)</label>
                      <input type="number" step="0.01" className="form-control" value={formData.other_charges} onChange={e => setFormData({ ...formData, other_charges: e.target.value })} />
                    </div>
                  </div>
                  <div className="alert border border-primary py-2 text-center" style={{ background: 'rgba(99,102,241,0.1)' }}>
                    <strong>Total: ₹{(
                      parseFloat(formData.maintenance_amount || 0) +
                      parseFloat(formData.water_charge || 0) +
                      parseFloat(formData.electricity_charge || 0) +
                      parseFloat(formData.other_charges || 0)
                    ).toLocaleString('en-IN')}</strong>
                  </div>
                </div>
                <div className="modal-footer border-secondary border-top">
                  <button type="button" className="btn btn-secondary bg-transparent" onClick={closeModal}>Cancel</button>
                  <button type="submit" className="btn btn-primary-gradient">
                    {editBill ? 'Update Bill' : 'Generate Bill'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default Billing;
